on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  chatgpt-code-generation:
    if: ${{ (github.event_name == 'issues' && 
             contains( github.event.label.name, 'AIPR')) || 
            (github.event_name == 'issue_comment' && 
             github.event.issue.pull_request &&
             contains( github.event.comment.body, 'Create PR with AIPR')) }}
    runs-on: ubuntu-latest
    steps:
    - name: ChatGPT Code Generation
      uses: alexanmtz/AIPR@master
